<?php

namespace Tests\Feature\Console;

use App\Enums\EmployeeAttendanceStatus;
use App\Models\Employee;
use App\Models\EmployeeAttendance;
use App\Models\NonSchoolDay;
use App\Models\ScanEvent;
use App\Models\SchoolSetting;
use App\Services\SchoolSettings;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Date;
use Tests\TestCase;

class MarkStaffAbsencesCommandTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        SchoolSetting::first()->update([
            'school_timezone' => 'Asia/Jakarta',
            'staff_absent_sweep_time' => '09:00:00',
            'school_operational_days' => [1, 2, 3, 4, 5],
        ]);
        app(SchoolSettings::class)->refresh();
    }

    protected function tearDown(): void
    {
        Date::setTestNow();

        parent::tearDown();
    }

    public function test_ac_16_05_sweep_marks_expected_active_employees_absent_and_skips_inapplicable_ones(): void
    {
        // Monday 2026-10-05, 09:00 Jakarta (02:00 UTC)
        Date::setTestNow('2026-10-05 02:00:00', 'UTC');

        // 1. Regular active employee with no record -> should be marked absent
        $regularActive = Employee::factory()->create(['name' => 'Guru Tetap', 'working_days' => null]);

        // 2. Part-timer working Monday (1) -> should be marked absent on Monday
        $partTimerMonday = Employee::factory()->create(['name' => 'Guru Senin', 'working_days' => [1, 3]]);

        // 3. Part-timer working Tuesday (2) only -> should be SKIPPED
        $partTimerTuesday = Employee::factory()->create(['name' => 'Guru Selasa', 'working_days' => [2, 4]]);

        // 4. Inactive employee -> should be SKIPPED
        $inactive = Employee::factory()->inactive()->create(['name' => 'Guru Nonaktif']);

        // 5. Employee who already checked in (present) -> should NOT be overwritten
        $alreadyPresent = Employee::factory()->create(['name' => 'Guru Hadir']);
        EmployeeAttendance::factory()->create([
            'employee_id' => $alreadyPresent->id,
            'date' => '2026-10-05',
            'status' => EmployeeAttendanceStatus::Present,
            'checked_in_at' => now(),
        ]);

        $this->artisan('staff-attendance:mark-absences')
            ->expectsOutput('Marked 2 employees absent for 2026-10-05.')
            ->assertSuccessful();

        // Verify regular active employee
        $record1 = EmployeeAttendance::where('employee_id', $regularActive->id)->where('date', '2026-10-05')->first();
        $this->assertNotNull($record1);
        $this->assertSame(EmployeeAttendanceStatus::Absent, $record1->status);
        $this->assertNull($record1->scan_method);
        $this->assertNull($record1->checked_in_at);

        // Verify part-timer Monday
        $record2 = EmployeeAttendance::where('employee_id', $partTimerMonday->id)->where('date', '2026-10-05')->first();
        $this->assertNotNull($record2);
        $this->assertSame(EmployeeAttendanceStatus::Absent, $record2->status);

        // Verify part-timer Tuesday has no record
        $this->assertNull(EmployeeAttendance::where('employee_id', $partTimerTuesday->id)->first());

        // Verify inactive has no record
        $this->assertNull(EmployeeAttendance::where('employee_id', $inactive->id)->first());

        // Verify already present remains present
        $presentRecord = EmployeeAttendance::where('employee_id', $alreadyPresent->id)->where('date', '2026-10-05')->first();
        $this->assertSame(EmployeeAttendanceStatus::Present, $presentRecord->status);

        // No scan_events generated by the sweep
        $this->assertSame(0, ScanEvent::count());
    }

    public function test_sweep_skips_non_school_days(): void
    {
        // Monday 2026-10-05, 09:00 Jakarta
        Date::setTestNow('2026-10-05 02:00:00', 'UTC');

        Employee::factory()->create();

        NonSchoolDay::factory()->create([
            'date' => '2026-10-05',
            'name' => 'Hari Libur Khusus',
        ]);

        $this->artisan('staff-attendance:mark-absences')
            ->expectsOutput('Non-school day (2026-10-05) — skipped.')
            ->assertSuccessful();

        $this->assertSame(0, EmployeeAttendance::count());
    }

    public function test_sweep_is_idempotent_on_rerun(): void
    {
        Date::setTestNow('2026-10-05 02:00:00', 'UTC');

        Employee::factory()->create();

        $this->artisan('staff-attendance:mark-absences')
            ->expectsOutput('Marked 1 employees absent for 2026-10-05.')
            ->assertSuccessful();

        // Second run: 0 new records created, no duplicate key errors
        $this->artisan('staff-attendance:mark-absences')
            ->expectsOutput('Marked 0 employees absent for 2026-10-05.')
            ->assertSuccessful();

        $this->assertSame(1, EmployeeAttendance::count());
    }
}
